### ISSUE TITLE
Top-Level Sidebar Fixes

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso-org.github.io#10]
### General Summary
When at the top-level of the site (currently `README.md`, soon `index.html`), the sidebar shows the top-level contents for the enso repo docs and there's no way to get to the enso repo docs top-level file. 

When at the top level of the site the nav should instead show the top-level file of the enso docs as the entry in the nav, in keeping with the rest of the site hierarchy.

### Motivation
Easy site navigation, future expandability.

**Comment by joenash** [comment]
> there's no way to get to the enso repo docs top-level file.

It's the bottom link. This is actually a bug in that the other sidebar entries are being shown erroneously, the sidebar is digging more than one subdirectory down.

**Comment by joenash** [comment]
Also need to add a check for being at `/` to hide the `Go back` button.

**Comment by joenash** [comment]
Fixed by https://github.com/luna/luna.github.io/commit/e610aec111865c82a77ece1d1812f2ffc54826d5
