### ISSUE TITLE
No Support for LFS Files

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso-org.github.io#19]
### General Summary
The docs site is breaking when trying to read a file tracked using Git LFS.

### Steps to Reproduce
Go [here](https://dev.enso.org/docs/runtime/function-call-flow.html) and see that the diagram doesn't render.

### Expected Result
The diagram renders as it does on GitHub.

### Actual Result
The diagram doesn't render.

**Comment by joenash** [comment]
Closing for now since LFS will no longer be used in luna/enso, however, this would have just been a simple addition to the GitHub Action to sync, which may as well be documented for the future in case we add an LFS repo. Will add to README.
