### ISSUE TITLE
Replace darkmode colour scheme with 'coal' scheme from mdbook

### ISSUE THREAD

**Issue by joenash** [enso-org/enso-org.github.io#27]
### General Summary
Source https://github.com/rust-lang/mdBook

### Motivation
Ara wants it

**Comment by iamrecursion** [comment]
Another issue that's just become apparent to me with the syntax highlighting, is that whitespace is shown differently from background (and shouldn't be) and the line-spacing is way too big. See [here](https://dev.enso.org/docs/enso/parser/architecture.html) for an example of the issues.

**Comment by joenash** [comment]
Cool, will look into it!
